version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - zedzhen

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - zedzhen
    ignore:
      - dependency-name: "sphinx-autobuild"
        versions: [ "<2025.8" ]
      - dependency-name: "Sphinx"
        versions: [ "<9" ]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - zedzhen
