repos:
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.25.0
    hooks:
      - id: pyproject-fmt
        files: (^|/)(pyproject|mypy_\w+)\.toml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        types: [python]
        language: python
        pass_filenames: false
        entry: python3 tools/mypy.py --fast
        additional_dependencies:
          - types-docutils~=0.22
          - mypy~=2.1
          - sphinx~=9.0
          - pydantic~=2.10
          - typing-extensions~=4.14
          - sqlalchemy~=2.0
